language: java

jdk:
- oraclejdk8

env:
  global:
  - secure: e96kKaqQiFpH1leNnf/NFd+CqWSBJYjmD6Hg8Bbbqo22Sq4cL/jFw2V0hzJiSBYpqIwnyifZWe2FaU0TRee/ne1bHcpUbxLXItkWuUjjPGeVEtS78uQwJ9vC+UpU+MF6mU0uIKF7PrFTbfxJIN6i/kfe2OC83E1m7fLrd8dY7UanaKYN6xw5t3lj0KEuycb2zwxRifTDEITe5F1szmukTf4FMmN611JoUSZtYVxGDyB5okfrlJDkBV2AvkfaUHQ2+MlPkIopHtn22WPghJ30FJs9k5/txQ9ixRBC9F6V5BR5prbOXhWrabKpUA4nuXB1GlRKW0yZa6QLeJDkQrX/WHb3+fIBsgXS4us/jB7vxRj9Hdgzk2PHMSNvTiZyap0GL5roMMHRA+kdgfe3N1vASC78Z8DcQjE5N7qkyECNm5YFBzrYs7MKJiJV3efiPTI+R5HWA4diaDP7Ex+/OetD+aDP+NRXjbIGnXlVi5UTl12UMFsFZIyyM9Jc7lU1RMYTWQ+UHztU1abXltR1oeljTECt6yqNKB5BT3s3QK9XkRFqIgTQefA2b7Lr3FPSc/iFQft3SFwTGl+caogFuZyaYp0f8KC7Ib08bdYekvAp7kVFefbDqXjV3zyX8h8sa2M1EmILp+YOepICzZguT4AtOJl9fAbrhgyedFisoNIrmao=
  - secure: ss26T4n8Fz5nTF+NxbN0MXBNgsNVOT4Wtw1vk0PTPITZHcb2kymazy31COrz3ERE10/XtgoePlG2MWT5AL8oS3l38JB4JC0L0R3f3Gkn5LHigVzfwFSyHNk55MlgNIXvtjWWj+th9II9A8hnwKwQz+AHhh31zZtFUMYfKos9hY6qgQSaysCe9YTEbYvVSt09zxRGTZjQoRXzoVZsExec0uEOIuc1VPEiIqcyQtPA29b75gW+31M67W8kBDyxrfIRfgNel4D8Uek2WGVMvzGNAHLwWQ0MjwIkSO763VIEjpllU8gEcBD/4qkRqdApjiZTROhgokOHgvEbpusm8U8AghAXl1nheZ23ymMV3m2cXqPfJDMgH0klWopqib/SJSzT4cgCaeB8R0sxCqlEhaNbdePNCZO/4jpX8pQxrF4Dkao2ssf2l7Hm0rUUbSQuVzTjrw6tADcgTU+M217XWynzHminC0VeW1/WpoiE2q35H8TYsjQNT40/u1jnfYOcfdp8MnwAzU7A6U9nnkAjvUiq7cT3PsNH0PVGv1VG+4W1cUubLLgPT3BtmqiqrUECAozH2KRap79QmE046cvQ06yvAic0JfCi318Qv2cOnDu5jhoQKf650bzsxzTNEGLtjhEcdOeh1WK+8mztbW1Tp2KtPLZytEE6Kkrsxfyhy5c/v3I=
  - secure: Wz0f38v4GvumplPM85/0xvMjp6c9wLKnHz99hHlTk5nSDvXrmGK0YJ402vrd1D0sFxjA9kBhqYgypYTlVOR4jyD6nAPVpqoKGiqno+sJ4ehUjHNLDNGIYw5vgqoJPmin1tKOzDVN7NbCdThqfTgRqy12BcJ80VoeXeW+AlOU7yMDdZe1arv/BokIEsHxQ+aeM5QdZ0b3XfEzCv9ISRN94Pc51ihh3II/X7aT/nAedzdo/J7E07Z1V8PY03RPdG2rEGdX3fjkVpgOixJwBb10j+IJc+gohq/MZBeESPaBlYnGvqtffa8fH54jEMvi1YAzmdxUwStJWV7RgoqjzwoZGXkPoEBgUjOe74qMkhyw0sbERDz/5bFREm9F1VRR4TlpNXCoLMcEHgaOSNp6EyL8LgNsHGdxrCJyZT2XIwLpMoyk169EDkfRsHjG82eKfWUF54oayVNSA5100St6CP+4zAkrwopPBkMgRanhqmhUMAsRalOvEx9NleHFahRiPESJPRz/tFlfnB2QG8Jnek+b0bKmsP6RCZS5A1RZEjC2R2qtdZ8393FSnWW/dapz/SDdkp+9BDKVR4+WBloEwm6Osf7kPVg76dwlj9HYrYy/2DC09Q40xETanTLoMFM42MuHkcLOfhwitpVD/y9kxoS6V4bqIiZxIDqiHMVe65EaIGg=
  - secure: ktjXx74mmxOnO/ToVxOn82z0H/OZ0SAwUYDYRlGjPd14gJUu+CGZKutiNZbQ89sJQRyKKhe0acpvgCE5DIdYUUp2aI5G+dgVdOpOI35Id8vkUASXeWSN4787hhq1bsusyNoM2IFieMn8RW9ctbXUv4AIksS0oBuDMRVU2ng3yqKAK/cCsbuwJhZozKXlQgQNLTj8Vkx+Kfk5d1Q94kKvFepw+Z4d+YQ19dtyu403ycmGn7OMTCJ5Qr1tr/kNgW+hWC1aWY1IgZIFTDR/tu3L/zzOhcBMH/qPaGD2/LFwl9glLFq6tfegjDtsfM3mI72wJaQSeuJYVMKNbz6PP9jiTGwTfLXBW/LGGZ9m996OoC3eMCrblLFZT1Hbe46EQn6zjhZ1oPln74WceexnGuAGMaKU6T4HX7sJKtW2hvOnjux6KSkHqlWg+GQqWEXDJ6bfgVfCQ4FmHfQ8gd5udpOai0yq56/ITXazsfk41/AXZaoQTVw6huTfdlGCLJ3QN10XENYmRfxbEYz/1H8x8jfeJnL3l2IevMUUiqHWQBFQM77cOfNm0ueDPNfa9K0pKJGhOVRb9Oqdfb+LpVjSGKvsXX07ezMoFRD92CArwez5KBkm604mfXfj/tbQHViv8pJdRVl/ZskYKMf4MntShpkozW5GmE/ZdrGIR/nLjg2IvaU=

install:
- echo "MAVEN_OPTS='-XX:+TieredCompilation -XX:TieredStopAtLevel=1'" > ~/.mavenrc
- "./mvnw -T4 -Dmaven.test.skip=true install"

jobs:
  include:
  - stage: test
    script: "./mvnw -P with-e2e-tests verify"
  - stage: deploy
    sudo: false
    services: []
    install: skip
    script: skip
    deploy:
      provider: script
      script: release/deploy.sh
      on:
        tags: true
        branch: master
