language: java

jdk:
- oraclejdk8

env:
  global:
  - secure: e96kKaqQiFpH1leNnf/NFd+CqWSBJYjmD6Hg8Bbbqo22Sq4cL/jFw2V0hzJiSBYpqIwnyifZWe2FaU0TRee/ne1bHcpUbxLXItkWuUjjPGeVEtS78uQwJ9vC+UpU+MF6mU0uIKF7PrFTbfxJIN6i/kfe2OC83E1m7fLrd8dY7UanaKYN6xw5t3lj0KEuycb2zwxRifTDEITe5F1szmukTf4FMmN611JoUSZtYVxGDyB5okfrlJDkBV2AvkfaUHQ2+MlPkIopHtn22WPghJ30FJs9k5/txQ9ixRBC9F6V5BR5prbOXhWrabKpUA4nuXB1GlRKW0yZa6QLeJDkQrX/WHb3+fIBsgXS4us/jB7vxRj9Hdgzk2PHMSNvTiZyap0GL5roMMHRA+kdgfe3N1vASC78Z8DcQjE5N7qkyECNm5YFBzrYs7MKJiJV3efiPTI+R5HWA4diaDP7Ex+/OetD+aDP+NRXjbIGnXlVi5UTl12UMFsFZIyyM9Jc7lU1RMYTWQ+UHztU1abXltR1oeljTECt6yqNKB5BT3s3QK9XkRFqIgTQefA2b7Lr3FPSc/iFQft3SFwTGl+caogFuZyaYp0f8KC7Ib08bdYekvAp7kVFefbDqXjV3zyX8h8sa2M1EmILp+YOepICzZguT4AtOJl9fAbrhgyedFisoNIrmao=
  - secure: jV1SOFgGqMSEE5hnh8OVOqKe6J66B51unOm/fmBBUbCYO2/t1RjxhG7tgh057qHmo9lCQerVu/lWN9h7vOhdbePumMmNI7coNujSCwrBwNsV/VrYLJZwdkKZOJ/SJE2Kb2rbETYyDx4Coz47eXHM6QBCaTO3WEoEA8//0UNMpogYJIFeqQZO1vtAKnmmYQ4yZFKvMXaO8PXkYmTdZbW1PApGUzQ/X+1FzN5+DNnMPWrK+9izisaN77L4I4GtXN1AsjS7Gt3UkSgsSgGUu8JZVnzjm2BgSZtTnE3g5WV1p6nBLGmRWjaujU5t0PJ+y8ah1gavxMtjjtQnugdn3IdVQ0GUJD7GKO+/qRSZUmHYk4khpV1/tr4YkKkHD6wZMz47xX5UUlAXybFnbfbn2tIOyTiAqq9HoMmT+WKlmtdgPwtnshXrW3eCVbPIpoz7mLyh+i73dyOKhcxP/G4L96yqxKwcYAK9CEUTfVvMVIojD8XsIli00gXFU8C5uTCTrRwN2er6wLmf01lG+Rjfv7wYKrPtCzngMRp8mXnymRlzcPjuu5tBqcTD45iNoQV7GX/sUF6n4ezmHC2LFd+dXx81zub4OLjNiJmjxUlkPB8wZDTbJg56HymeqILb/qckl43FO2Zx4oO9UIiU7X7d6HPOhCvbCX3p6LW5fHIDAKZn4Q4=
  - secure: Wz0f38v4GvumplPM85/0xvMjp6c9wLKnHz99hHlTk5nSDvXrmGK0YJ402vrd1D0sFxjA9kBhqYgypYTlVOR4jyD6nAPVpqoKGiqno+sJ4ehUjHNLDNGIYw5vgqoJPmin1tKOzDVN7NbCdThqfTgRqy12BcJ80VoeXeW+AlOU7yMDdZe1arv/BokIEsHxQ+aeM5QdZ0b3XfEzCv9ISRN94Pc51ihh3II/X7aT/nAedzdo/J7E07Z1V8PY03RPdG2rEGdX3fjkVpgOixJwBb10j+IJc+gohq/MZBeESPaBlYnGvqtffa8fH54jEMvi1YAzmdxUwStJWV7RgoqjzwoZGXkPoEBgUjOe74qMkhyw0sbERDz/5bFREm9F1VRR4TlpNXCoLMcEHgaOSNp6EyL8LgNsHGdxrCJyZT2XIwLpMoyk169EDkfRsHjG82eKfWUF54oayVNSA5100St6CP+4zAkrwopPBkMgRanhqmhUMAsRalOvEx9NleHFahRiPESJPRz/tFlfnB2QG8Jnek+b0bKmsP6RCZS5A1RZEjC2R2qtdZ8393FSnWW/dapz/SDdkp+9BDKVR4+WBloEwm6Osf7kPVg76dwlj9HYrYy/2DC09Q40xETanTLoMFM42MuHkcLOfhwitpVD/y9kxoS6V4bqIiZxIDqiHMVe65EaIGg=
  - secure: U1zlQhqN9ghHJ0MaZDDcqg7sp32tPG0tPnU+hB+niCI+wRycr9A4pKHqenrty8fdDZDB2TFUqeWYQDrtFJdGfSLgdEgtCf2aboD6PJptPSCn6xNh9Ay3xFyVhF8+vN8niP4Uh+aRSBNcSwtc/4VHfRlyRVSb2wBBhC4uCDJZQG1+bJ2rjGsbEhkO1yUDUsrRl2biaUhuGPz1PZ1m7QSNn6JpOI7TQagZ7YQBdCrBgZG2ITzZuPF4itNHbMbToAUsOshliOHZ6GFWYJ81JKu1Ka+WsPk1Y6cO7Er1iPEkZhEjUPxylHgSJpqgKvCDds7DX6UXBJF3sujjJSAn2SayWMYPfQSsEYWIhXogrZMHMQCY4gll3kyHFcCNFmb26Gb21pVZp201PSJk7W/hVp3HfUWw3J2kcr3NHPPJKmt17ZcVmSuJ+AQJmOb6Qvu6rbsNYw0rOW7YcU7VTqRG2tU05nBswALqdUetViuSgGq0kCDO5d3qXHWPGP8QvENPaCM/3qFR05VOnxCmpnHPTdChpiHy/CoOabwjmCDFaamAmRkXtO2hWIoVeQdYqw9fBGXy/0HnQ/AR7/e5NaaD6qrcWOZF+agV91nL1lshGTVh94lWm4RkuqVUe2olzlPWUTagVkYbZux6ed1L1LlI7nrwb/LCzdzBBSrj3Mp9ANRc9K8=

install:
- echo "MAVEN_OPTS='-XX:+TieredCompilation -XX:TieredStopAtLevel=1'" > ~/.mavenrc
- "./mvnw -T4 -Dmaven.test.skip=true install"

jobs:
  include:
  - stage: test
    script: "./mvnw -P with-e2e-tests verify"
  - stage: deploy
    sudo: false
    services: []
    install: skip
    script: skip
    deploy:
      provider: script
      script: release/deploy.sh
      on:
        tags: true
        branch: master
